### ISSUE TITLE
Bəzi tapşırıqlar 

### ISSUE THREAD

**Issue by EldanizAkbar** [ismayilzadesenan/PragmatechFoundationProject#1]
Zəhmət olmasa aşağıdakı tapşırıqları tez bir zamanda həll et.

- [x] Lazımsız fayllları sil.(məs: week1-day6.txt)
- [x] TASK qovluğundakı **img** folderini hansı tapşırıq üçün yazmısansa həmin tapşırıqla eyni qovluğa qoy.
- [x] Layihə qovluğundakı qovluqları sil. Həftənin günləri adlı qovluqlar yalnız TASK qovluğunda olmalıdır. Layihə qovluğunda əsasən html, css, img, js qovluqları olmalıdır.

**Comment by ismayilzadesenan** [comment]
tapsiriq hell olundu
