### ISSUE TITLE
Bəzi tapşırıqlar

### ISSUE THREAD

**Issue by EldanizAkbar** [ismayilzadesenan/PragmatechFoundationProject#5]
Zəhmət olmasa aşağıdakı problemləri tez bir zamanda həll et.

- [x] Layihəndə bəzi yerlərdə grid problemi var. Zəmət olmasa onları düzəlt.
- [x] Layihəndə bəzi div tag-lari açılıb amma bağlanmayıb ya da yalnış yerdə bağlanıb. Zəhmət olmasa onları düzəlt.

**Comment by ismayilzadesenan** [comment]
grid problemini hell etdim aiq qalan divler baqlandi
